#!/usr/bin/env zsh
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd

# If hyprland config was involved, reload
if [[ "$STOW_FOLDERS" == *"hypr"* ]] then
    echo "Reloading Hyprland..."
    hyprctl reload
fi
