#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed wl-clipboard grim slurp
sudo pacman -S --noconfirm --needed wayland waybar waylock pavucontrol
sudo pacman -S --noconfirm --needed ttf-font-awesome ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
