#!/usr/bin/env bash

sudo apt install -y zsh tmux stow vim

sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt update
sudo apt install neovim tree-sitter-cli -y


sudo apt install -y make curl

sudo apt install -y golang-go python3-venv 


curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
source ~/.bashrc
nvm install --lts

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


sudo snap install alacritty --classic

mkdir -p ~/.local/share/fonts/JetBrainsMono
wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
unzip JetBrainsMono.zip -d ~/.local/share/fonts/JetBrainsMono
rm JetBrainsMono.zip
fc-cache -fv
